### ISSUE TITLE
Add a page for the server events calendar embed

### ISSUE THREAD

**Issue by DoomsdayOrange** [RE-SS3D/SS3D-Website#51]
Self explanatory

https://calendar.google.com/calendar/u/2/r?tab=oc&pli=1

<iframe src="https://calendar.google.com/calendar/embed?src=f7ttpb0t68tst1feejt9k02660%40group.calendar.google.com&ctz=America%2FLos_Angeles" style="border: 0" width="800" height="600" frameborder="0" scrolling="no"></iframe>

**Comment by cosmiccoincidence** [comment]
Is this even needed? You had a big plan to do a bunch of events, made a calendar, and made like 2 events. Now the events channel in the discord is just another example of how dead we are at the moment.

**Comment by cosmiccoincidence** [comment]
Events died off. Not that I'm against them in concept but hosting like 2 jackbox events a year and just make penis jokes isn't that appealing to most. We have since archived the events channel in discord. We can revisit the calendar idea if we actually start hosting more appealing events.
